frontend/desktop/public/cc/appstore.svg, frontend/desktop/public/cc/cronjob.svg, frontend/desktop/public/cc/database.svg, frontend/desktop/public/cc/devbox.svg, frontend/desktop/public/cc/kubepanel.svg, frontend/desktop/public/cc/launchpad.svg, frontend/desktop/public/cc/oss.svg, frontend/desktop/public/cc/terminal.svg, frontend/desktop/src/components/account/GuideModal.tsx, frontend/packages/ui/src/components/MyTable/index.tsx, frontend/providers/dbprovider/src/hooks/driver.tsx, frontend/providers/dbprovider/src/pages/db/detail/index.tsx, frontend/providers/dbprovider/src/pages/db/edit/index.tsx, frontend/providers/dbprovider/src/pages/dbs/components/dbList.tsx, frontend/providers/dbprovider/src/store/guide.ts, frontend/providers/dbprovider/src/styles/reset.scss, frontend/providers/template/src/store/guide.ts
=> add logo & fix devbox ci & db guide

frontend/desktop/src/components/account/index.tsx, frontend/desktop/src/components/cc/Sign.tsx, frontend/desktop/src/pages/_app.tsx, frontend/desktop/src/stores/session.ts
---------
Co-authored-by: mlhiter <3076438032@qq.com>
=> feat(desktop): remember me

frontend/providers/devbox/app/[lang]/(platform)/(home)/components/DevboxList.tsx, frontend/providers/devbox/components/PodLineChart.tsx
---------
Co-authored-by: mlhiter <3076438032@qq.com>
=> fix(devbox): echart tooltip show bug&total page bug

frontend/providers/accountcenter/src/pages/api/billing/appBilling.ts
=> update api appbilling

frontend/desktop/src/pages/api/auth/oauth/google/index.ts, frontend/desktop/src/services/backend/persistImage.ts, frontend/providers/accountcenter/src/pages/api/billing/appBilling.ts, frontend/providers/accountcenter/src/pages/api/plan/lastTransaction.ts, frontend/providers/accountcenter/src/pages/api/plan/upgradeAmount.ts, frontend/providers/accountcenter/src/schema/plan.ts
=> Account center

frontend/desktop/prisma/global/schema.prisma, frontend/desktop/src/services/backend/cronjob/syncUserPlan.ts, frontend/desktop/src/services/backend/svc/downGrade.ts, frontend/desktop/src/types/response/syncPlan.ts, frontend/providers/accountcenter/src/pages/api/plan/creditsUsage.ts, frontend/providers/accountcenter/src/schema/plan.ts
disable merge
fix(desktop): add downGrade
=> fix-some-bug

frontend/providers/accountcenter/src/components/Plans/Credits.tsx, frontend/providers/accountcenter/src/utils/format.ts
=> fix: 修改字段，修复bug

frontend/providers/accountcenter/src/pages/api/user/delete.ts, frontend/providers/accountcenter/src/pages/api/user/getInfo.ts, frontend/providers/accountcenter/src/schema/user.ts
=> feat:add createdAt for getinfo

frontend/providers/accountcenter/src/pages/setting/components/deleteAccount.tsx
=> feat: icon修改 居中

frontend/desktop/src/components/account/GuideModal.tsx, frontend/desktop/src/components/account/index.tsx, frontend/desktop/src/components/cc/Sign.tsx, frontend/desktop/src/components/cc/Workspace.tsx, frontend/desktop/src/components/cc/auth/useWechat.tsx, frontend/desktop/src/components/signin/auth/useWechat.tsx, frontend/desktop/src/components/team/RenameTeam.tsx, frontend/desktop/src/pages/api/auth/phone/bind/sms.ts, frontend/desktop/src/pages/api/v1alpha/account/updateGuide.ts, frontend/desktop/src/pages/callback.tsx, frontend/desktop/src/pages/callbackVerify.tsx, frontend/desktop/src/pages/index.tsx, frontend/desktop/src/services/backend/auth.ts, frontend/desktop/src/services/backend/cronjob/index.ts, frontend/desktop/src/services/backend/sms.ts, frontend/desktop/src/services/request.ts, frontend/desktop/src/stores/config.ts, frontend/desktop/src/stores/initWorkspace.ts, frontend/providers/accountcenter/src/pages/api/billing/appBilling.ts, frontend/providers/accountcenter/src/pages/api/payment/recharge.ts, frontend/providers/accountcenter/src/pages/api/plan/update.ts, frontend/providers/accountcenter/src/service/backend/auth.ts, frontend/providers/accountcenter/src/service/backend/region.ts, frontend/providers/devbox/app/api/platform/resourcePrice/route.ts, frontend/providers/devbox/components/PriceBox.tsx, frontend/providers/devbox/utils/format.ts
=> Remove debug console.log statements from codebase

frontend/desktop/src/pages/api/auth/email/bind/sms.ts, frontend/desktop/src/pages/api/auth/email/bind/verify.ts, frontend/desktop/src/pages/api/auth/email/changeBinding/newSms.ts, frontend/desktop/src/pages/api/auth/email/changeBinding/oldSms.ts, frontend/desktop/src/pages/api/auth/email/changeBinding/verifyNew.ts, frontend/desktop/src/pages/api/auth/email/changeBinding/verifyOld.ts, frontend/desktop/src/pages/api/auth/email/unbind/verify.ts, frontend/desktop/src/pages/api/auth/password/exist.ts, frontend/desktop/src/pages/api/auth/password/index.ts, frontend/desktop/src/pages/api/auth/password/modify.ts, frontend/desktop/src/pages/api/auth/phone/bind/sms.ts, frontend/desktop/src/pages/api/auth/phone/bind/verify.ts, frontend/desktop/src/pages/api/auth/phone/changeBinding/newSms.ts, frontend/desktop/src/pages/api/auth/phone/changeBinding/oldSms.ts, frontend/desktop/src/pages/api/auth/phone/changeBinding/verifyNew.ts, frontend/desktop/src/pages/api/auth/phone/changeBinding/verifyOld.ts, frontend/desktop/src/pages/api/auth/phone/sms.ts, frontend/desktop/src/pages/api/auth/phone/unbind/sms.ts, frontend/desktop/src/pages/api/auth/phone/unbind/verify.ts, frontend/desktop/src/pages/api/auth/phone/verify.ts, frontend/desktop/src/pages/api/auth/publicWechat/getWechatQR.ts, frontend/desktop/src/pages/api/auth/publicWechat/getWechatResult.ts, frontend/desktop/src/pages/api/auth/publicWechat/handleWechat.ts, frontend/desktop/src/pages/api/multiRegion/workspace/list/index.ts, frontend/desktop/src/pages/api/multiRegion/workspace/list/region.ts, frontend/desktop/src/pages/api/v1alpha/password/signin.ts, frontend/desktop/src/pages/api/v1alpha/password/signup.ts
=> Disable API endpoints with cc not support error

frontend/desktop/src/components/cc/Sign.tsx, frontend/desktop/src/components/cc/auth/AuthList.tsx
Update the scope string to include profile and email in the correct order and modify the proxy login logic to accommodate these changes
=> Update Google OAuth scope and proxy logic

frontend/providers/objectstorage/src/components/buckConfig/ConfigHeader.tsx, frontend/providers/objectstorage/src/components/buckConfig/Configmain.tsx
=> Change Button onClick to handle Yaml export, close Yaml tab

frontend/providers/accountcenter/src/pages/index.tsx, frontend/providers/accountcenter/src/pages/setting/components/deleteAccount.tsx
=> refactor: 支付类型来判断需不需要进入升级轮询页面

frontend/desktop/src/components/cc/Workspace.tsx, frontend/desktop/src/pages/api/auth/initRegionToken.ts, frontend/desktop/src/pages/switchRegion.tsx, frontend/desktop/src/schema/auth.ts
=> fix switch region init

frontend/desktop/prisma/global/schema.prisma, frontend/desktop/src/components/notification/index.tsx, frontend/desktop/src/pages/api/account/referral/index.ts, frontend/desktop/src/pages/api/account/referral/stats.ts, frontend/desktop/src/services/backend/globalAuth.ts, frontend/desktop/src/services/backend/kubernetes/user.ts, frontend/desktop/src/types/license.ts, frontend/desktop/src/utils/json2Yaml.ts, frontend/providers/accountcenter/prisma/global/schema.prisma, frontend/providers/accountcenter/src/pages/api/referral/index.ts, frontend/providers/accountcenter/src/pages/api/referral/stats.ts
=> Refactor referral

frontend/desktop/src/services/backend/globalAuth.ts
* Modify the GitHub OAuth binding flow to use the new bindProviderV2Svc
* Update globalAuth to handle GitHub binding configuration
* Refactor bindProviderSvc to support GitHub binding configuration
* Remove redundant code and improve error handling
=> Update GitHub OAuth binding service and related logic

frontend/desktop/src/pages/api/account/referral/index.ts, frontend/providers/accountcenter/src/pages/api/referral/index.ts
=> refactor: fix verify, change referralCode to link

frontend/providers/accountcenter/src/pages/usage/components/usage.tsx
=> fix account-center

frontend/desktop/src/pages/api/auth/namespace/abdicate.ts
=> fix abdicate

frontend/desktop/data/config.yaml, frontend/desktop/public/locales/en/common.json, frontend/desktop/public/locales/zh/common.json, frontend/desktop/src/components/account/index.tsx, frontend/desktop/src/types/system.ts, frontend/providers/accountcenter/public/locales/en/common.json, frontend/providers/accountcenter/src/pages/referral/index.tsx, frontend/providers/objectstorage/src/services/request.ts, frontend/providers/objectstorage/src/utils/user.ts
=> Refactor text

frontend/providers/template/src/components/layout/appmenu.tsx, frontend/providers/template/src/pages/develop/index.tsx, frontend/providers/template/src/utils/json-yaml.ts
=> feat: 添加debug按钮

frontend/providers/accountcenter/src/pages/api/user/delete.ts, frontend/providers/accountcenter/src/service/backend/region.ts
=> fix delete-user

frontend/desktop/src/components/AppDock/index.tsx, frontend/desktop/src/components/region/RegionToggle.tsx, frontend/desktop/src/pages/api/platform/getCloudConfig.ts, frontend/desktop/src/types/system.ts
=> feat:swith region

frontend/providers/applaunchpad/src/utils/deployYaml2Json.ts, frontend/providers/dbprovider/src/utils/json2Yaml.ts
=> refactor: set cpu to 1/20

frontend/providers/accountcenter/src/service/auth.ts
=> Update auth.ts to adjust token expiration in development

frontend/desktop/src/services/backend/cronjob/deleteUserCr.ts, frontend/desktop/src/services/backend/cronjob/syncUserPlan.ts
=> Add missing transaction info validation in cronjob services

frontend/desktop/src/components/v2/PhoneCheck.tsx, frontend/desktop/src/components/v2/Sign.tsx
refactor: sign in/up  backend
Update translation keys and remove unnecessary dependencies
Refactor PhoneCheck and Sign components
Update PhoneCheck.tsx to streamline phone verification flow and improve state management. Refactor Sign.tsx to handle different sign-in methods based on layout configuration. Add version field to LayoutConfigType in system.ts to support locale-specific configurations.
=> Update RechargeModal to simplify bonus display and fix .gitignore

frontend/desktop/src/stores/signup.ts, frontend/providers/template/src/pages/_document.tsx
Improve the user experience by showing a dynamic countdown when a new link can be requested. The countdown updates every second, enhancing clarity and responsiveness.
onboarding for usw
add cloudflare
Refactor EmailCheck and update signup store
Update EmailCheck.tsx to improve token handling and error recovery. Refactor signup store to manage startTime more robustly. Add brand-specific meta tags to _document.tsx.
=> Update countdown display in PhoneCheck component

frontend/desktop/src/components/v2/Workspace.tsx
Improve user guide for applaunchpad, dbprovider, and devbox providers. Update driver configurations and add new steps for better user experience. Update guide messages and images for consistency. Update stores and hooks for managing guide state. Add new components and pages for guiding users through the application creation and deployment process. Update dependencies and configuration files for compatibility. Update locales for translations.
=> fix initworkspace

frontend/desktop/src/components/v2/Sign.tsx, frontend/desktop/src/services/backend/sms.ts
=> fix: input

frontend/desktop/src/pages/api/platform/getAuthConfig.ts
=> Remove debug log from genResAuthClientConfig function

frontend/desktop/src/components/v2/EmailCheck.tsx, frontend/desktop/src/pages/api/platform/getAuthConfig.ts
=> Onboarding

frontend/desktop/src/api/platform.ts, frontend/desktop/src/components/account/index.tsx, frontend/desktop/src/components/cc/Cost.tsx, frontend/desktop/src/components/desktop_content/index.tsx, frontend/desktop/src/components/desktop_content/limitedOfferModal.tsx, frontend/desktop/src/pages/api/desktop/getResource.ts, frontend/desktop/src/types/user.ts, frontend/desktop/src/utils/format.ts
=> add traffic

frontend/providers/costcenter/src/components/invoice/InvoiceDownloadModal.tsx, frontend/providers/costcenter/src/components/invoice/InvoicePrintableView.tsx
=> feat(costcenter): multiline invoice info
